### ISSUE TITLE
Fetched files not added to output of getBagContents()

### ISSUE THREAD

**Issue by mjordan** [scholarslab/BagItPHP#10]
Using the code in the "Reading a bag" example, with a bag that produces no errors and that has a fetch.txt, I was expecting the files identified in fetch.txt to end up in the same output directory as my payload files.

I can confirm that the remote file is being downloaded to the temporary directory with the rest of the payload files, but it is not being added to the output of getBagContents().  Is the intent that it get added to that array or do fetched files need to be handled separately? If the latter is the case, the example should illustrate how they could be copied like the payload files into the 'final/destination/' directory.

**Comment by whikloj** [comment]
@mjordan Is this still an issue or can it be closed?

**Comment by whikloj** [comment]
@mjordan &lt;bump&gt;

**Comment by mjordan** [comment]
Still happening. Here's the script that I'm using to create the bag:

```php
<?php

require_once 'BagItPHP/lib/bagit.php';

define('BASE_DIR', 'testbag');

// define some metadata to add to bag-info.txt
$baginfo = array('First-Tag' => 'This is the first tag value',
  'Second-Tag' => 'This is the second tag value'
);

// create a new bag at BASE_DIR
$bag = new BagIt(BASE_DIR, true, true, true, $baginfo);

// add a file; these are relative to the data directory
$bag->addFile('baz.txt', 'baz.txt');

// add additional metadata to bag-info.txt
$bag->setBagInfoData('Third-Tag', 'This is the third tag value');

// add some entries to fetch.txt
$bag->fetch->add('http://97.107.189.30/sites/default/files/content_browser_icon.png', 'foo.png');

// update the hashes
$bag->update();

// create a tarball
$bag->package('testbag');
```
Here's the script I'm using to read the bag:

```php
<?php

require_once 'BagItPHP/lib/bagit.php';

// use an existing bag
$bag = new BagIt('testbag.tgz');

// validate the bag
$bag->validate();

// only execute if a valid bag
if (count($bag->getBagErrors()) == 0) {
  // retrieve remote files
  $bag->fetch->download();

  // copy files
  foreach ($bag->getBagContents() as $filename) {
    copy($filename, 'output/foo/'. basename($filename));
  }
}
```
The PNG is not copied out to `output/foo`.

One thing that is strange, `testbag/fetch.txt` contains duplicate entries:

```
http://97.107.189.30/sites/default/files/content_browser_icon.png - foo.png
http://97.107.189.30/sites/default/files/content_browser_icon.png - foo.png
```

When I use the script provided in https://github.com/scholarslab/BagItPHP/issues/10#issuecomment-30945699, the fetched file is still not being copied into the output directory.

**Comment by whikloj** [comment]
Oh I see, there is no validation of the fetch file to put it into the data directory, so when you open the tar it looks like
```
-rw-r--r--  1 whikloj  staff   119  2 Dec 11:23 bag-info.txt
-rw-r--r--  1 whikloj  staff    55  2 Dec 11:18 bagit.txt
drwxr-xr-x  3 whikloj  staff    96  2 Dec 11:32 data
-rw-r--r--  1 whikloj  staff    83  2 Dec 11:20 fetch.txt
-rw-r--r--  1 whikloj  staff  5101  2 Dec 11:32 foo.png
-rw-r--r--  1 whikloj  staff    54  2 Dec 11:23 manifest-sha1.txt
-rw-r--r--  1 whikloj  staff   215  2 Dec 11:23 tagmanifest-sha1.txt
```
🤦‍♂ I'll see what I can do.

**Comment by whikloj** [comment]
I have a fix for this, but I will also note that `$bag->validate()` doesn't touch the fetch file and therefore has never actually validated a bag that uses a fetch file.

https://github.com/scholarslab/BagItPHP/blob/master/lib/bagit.php#L342-L352

**Comment by whikloj** [comment]
@mjordan regarding the duplicate entries in your fetch.txt. If you ran the script twice and didn't delete the `testbag/` directory between then you would add the same line again. There is no check that you don't add a URL twice or a file twice. The `add()` function just pushes the data onto the internal array and writes it out to the file.

I just tried once again and I only see the one line in the fetch.txt.

But if I run your script again it re-opens the bag created by the last run and adds the URL again.

```
[/sw/var/www/DAM2/BagItPHP] 
> ./test.php 

[/sw/var/www/DAM2/BagItPHP] 
> cd testbag 

[/sw/var/www/DAM2/BagItPHP/testbag] 
> cat fetch.txt 
http://umanitoba.ca/libraries/images/icons/et/roboto/50_height/hours.png - foo.png

[/sw/var/www/DAM2/BagItPHP/testbag] 
> cd ../

[/sw/var/www/DAM2/BagItPHP] 
> ./test.php   

[/sw/var/www/DAM2/BagItPHP] 
> cd testbag 

[/sw/var/www/DAM2/BagItPHP/testbag] 
> cat fetch.txt 
http://umanitoba.ca/libraries/images/icons/et/roboto/50_height/hours.png - foo.png
http://umanitoba.ca/libraries/images/icons/et/roboto/50_height/hours.png - foo.png
```

**Comment by mjordan** [comment]
I may have ran it twice. I'll retest and let you know.

**Comment by whikloj** [comment]
@mjordan &lt;bump&gt; on the retest results and could you have a look at #33 and see if it resolves this issue.

**Comment by mjordan** [comment]
Will do, out of the office until Thursday though.

**Comment by mjordan** [comment]
OK, your PR makes this work as intended. You were right about the double entries in fetch.txt - sorry about that. But, now that I have created a bag with a fetch, when I read it, the fetched file ends up in the bag's `data` directory. I'll approve the PR.
