### ISSUE TITLE
Remove line breaks from file encoding

### ISSUE THREAD

**Issue by ghalusa** [scholarslab/BagItPHP#19]
**From PHP** 

Notice: iconv(): Wrong charset, conversion from `UTF-8\r' to `UTF-8' is not allowed at...

**Solution**

lib/bagit_utils.php
readFileText method, Line 219, add:

```
    // Remove line breaks from $fileEncoding.
    $fileEncoding = preg_replace( '/\r|\n/', '', $fileEncoding );
```

**Pull Request https://github.com/scholarslab/BagItPHP/pull/18**

**Comment by ghalusa** [comment]
Hi @erochest - seems like BagItPHP is no longer maintained, with the last commit taking place on Aug 25, 2015. Is this a safe assessment?

**Comment by lotharthesavior** [comment]
I worked with this package from 2016 to 2017, and in 2018 I'm still using it for particular stuff, but I forked since 2016 because of the time. My knowledge in the BagIt standard is limited, but let me know If I can help, @ghalusa

**Comment by ghalusa** [comment]
Hi @lotharthesavior,

I'm just looking to get this pull request merged https://github.com/scholarslab/BagItPHP/pull/18

That way, it can get into the Packagist Repo, so I don't need to overwrite the core library (as I'm doing presently).

**Comment by lotharthesavior** [comment]
Hey, @ghalusa , 

I see what you mean. Just in case you want to move forward with something more maintainable than changing the library source while you wait, I can suggest 2 options:

1. (the way I did) fork this project, and add a code like this to your composer.json (this is how I'm doing with mine):
```json
{
    "repositories": [
        {
            "url": "https://github.com/lotharthesavior/BagItPHP.git",
            "type": "vcs"
        },
    ],
    "require": {
        ...
        "lotharthesavior/bagit": "dev-master",
        ...
    }
}
```
For this option, you composer.json must mention the name like mine did:
```json
{
    "name": "lotharthesavior/bagit",
    "version": "0.3.2",
    "require": {
        "pear/archive_tar": "~1.3"
    },
    "require-dev": {
        "phpunit/phpunit": "~4.4",
        "phpdocumentor/phpdocumentor": "2.*",
        "pdepend/pdepend" : "2.1.0",
        "phpmd/phpmd" : "@stable",
        "sebastian/phpcpd": "*",
        "squizlabs/php_codesniffer": "2.*",
        "mayflower/php-codebrowser": "~1.1"
    },
    "autoload": {
        "psr-4": {
            "Lotharthesavior\\BagItPHP\\": "lib/"
        }
    }
}
```
2. Create an account on packagist.org and put your repository available there.

I hope this helps.
Cheers,
Savio Resende

**Comment by ghalusa** [comment]
Hi @lotharthesavior,

Yeah, I've done this before with other libraries. I was just trying to avoid it since the project I'm working on is enterprise level.

I guess I may have no other option since BagItPHP is no longer actively being maintained.

Thanks for your time!

**Comment by whikloj** [comment]
Hey @ghalusa and @lotharthesavior,

I ran into the same issue as you both, and am working with the ScholarLab people and another BagItPHP fan to get this maintained again. Sorry for the inconvenience and hopefully we can be more responsive in the future.

**Comment by lotharthesavior** [comment]
That’s great! Let me know if I can help. I could reserve some time once in a while to this project because I’m a fan of archives science, and even though I’m not a specialist, I would love to see this succeeding.

**Comment by whikloj** [comment]
@lotharthesavior that would be awesome.
I guess the best would be some review of #25. I tried to update the code base but also start working towards BagIt 1.0 compliance. So any comments/suggestions from a user standpoint or (if you like reading specifications) from a spec compliance standpoint would be appreciated.

**Comment by whikloj** [comment]
Hey @lotharthesavior just wanted to let you know I've actually moved my 1.0 compliance stuff to a [new implementation](https://github.com/whikloj/BagItTools). I was worried that I am not well enough versed that trying to fix the problems here I might just break more things. So I'm going to review these PRs but leave this as is otherwise. I just wanted to let you know.

**Comment by whikloj** [comment]
Resolved with https://github.com/scholarslab/BagItPHP/commit/1db9eed7e9f9d90f8bf0a20472b7cb6cf595d168
