### ISSUE TITLE
Methods do not match function

### ISSUE THREAD

**Issue by whikloj** [scholarslab/BagItPHP#22]
There are [`getBagInfo()`](https://github.com/scholarslab/BagItPHP/blob/develop/lib/bagit.php#L252), [`getBagInfoKeys()`](https://github.com/scholarslab/BagItPHP/blob/develop/lib/bagit.php#L563) and [`getBagInfoData($key)`](https://github.com/scholarslab/BagItPHP/blob/develop/lib/bagit.php#L576) functions.

But `getBagInfo()` actually refers to information parsed from the `bagit.txt` where the other two refer to information parsed from the `bag-info.txt` file.

Seems like `getBagInfo()` should have a different name, like `getBagDeclaration()`?

**Comment by mjordan** [comment]
Agreed, but if we're changing the API, how should we handle notifying people whose scripts that might affect? Maybe use composer to notify people of deprecations (assumes people will update using composer).

**Comment by whikloj** [comment]
Won't fix
