### ISSUE TITLE
Attempted to load class "ZipArchive" from the global namespace.  

### ISSUE THREAD

**Issue by whikloj** [scholarslab/BagItPHP#23]
Related to https://github.com/mjordan/islandora_bagger/issues/38

This is where your installed version of PHP does not have the Zip extension installed which BagItPHP assumes. This results in an error like.
```
In bagit_utils.php line 437:
                                                                   
  Attempted to load class "ZipArchive" from the global namespace.  
  Did you forget a "use" statement?                                
```

**Comment by mjordan** [comment]
@whikloj Zip is installed:  output from `php -i | grep -i zip` includes "ZIP-based phar archives => enabled".

**Comment by mjordan** [comment]
`sudo apt-get install php7.2-zip` got it to work.
